services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Bogota
      - DOCKER_MODS=linuxserver/mods:universal-calibre
    volumes:
      - /home/apraghatyus/homelab/calibre-web/config:/config
      - /mnt/nas/media/books:/books:rslave
    ports:
      - 8083:8083
    restart: unless-stopped
    mem_limit: 512m
    cpus: 1.0
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8083 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
